name: amun

evaluate_each_epoch: true

trainer:
  max_epochs: 10

optim:
  name: sgd
  lr: 0.01
  momentum: 0.9           # only used if sgd
  weight_decay: 0.0
  nesterov: false         # only used if sgd
  betas: [0.9, 0.999]     # only used if adamw
  exclude_wd_norm_bias: true  # only used if adamw

scheduler:
  name: none

attack:
  epsilon_init: 0.1
  steps: 50
  step_factor: 0.1
  max_rounds: 6

use_weighted_loss: false
retain_weight: 0.5
forget_weight: ${eval:1 - ${.retain_weight}}

use_retain: true
use_forget: true
